### ISSUE TITLE
MySQLDumper incompatible with PHP 7

### ISSUE THREAD

**Issue by jpretired** [JustCarmen/fancy_database_backup#1]
I upgraded my Ubuntu to 16.04 and with this PHP upgraded to version 7.
MySQLDumper does not work as it calls mysql_connect() which is not in PHP7 any more.
I found its author annoucement here: http://forum.mysqldumper.de/ende-des-projekts-mysqldumper-t7541.html
And a bug report and its solution here: http://forum.mysqldumper.de/php-7-and-mysqli-t7496.html
I tried the solution but it did not work for me. So for now I am leaving MySQLDumper.
Maybe you will be more lucky, if you are still interested in this product.
Cheers, Josef

**Comment by JustCarmen** [comment]
Thanks for this information. I've thought about it but I've decided that I will not try to make the module and mysqldumper compatible with PHP7.

This module only provides a platform within the control panel of webtrees to let mysqldumper do his job, nothing more. I have no plans to alter the code of mysqldumper.

So as long as PHP5 is officially supported I will keep this module open and when no one stands up before the end of this period to take over mysqldumper from the current developer this will mean the end of this module.

**Comment by mpwt** [comment]
Take a look at [MyOOSDumper](http://doku.oos-shop.de/myoos-benutzerhandbuch/ueber-myoos/eine-einfuehrung-in-das-myoos-shopsystem/ueber-mysqldumper/). It works with PHP7 again. I have tested it on my site. It looks as it is the further development of MySQLDumper.

**Comment by JustCarmen** [comment]
Thanks for this information. I will look into this.
