### ISSUE TITLE
I cannot write to file "config.php". Please use your FTP program and chmod this file to 0777.

### ISSUE THREAD

**Issue by impartit** [JustCarmen/fancy_database_backup#2]
Cannot install on Windows WAMP server with this error! No file named config.php

**Comment by JustCarmen** [comment]
Hi I've just commited an example file which you can download from here and then upload to your server.

Normally config files are not in a repository because they contain private information. I have removed the personal data from this file.

Today I've received two emails from two different addresses within 10 minutes from each other with the same issue. I assume they are both from you, so I consider them both solved.

**Comment by impartit** [comment]
Carmen,

Thanks for the prompt reply. I have copied the config.php file you sent to
the www/vendor/r23/msd directory of my WINDOWS WAMP (so no CHMOD possible)
server and "no cigar". The database backup module Installation still gives
the error "I cannot write to file "config.php". Please use your FTP program
and chmod this file to 0777". Please advise further.

**Comment by impartit** [comment]
Looking at the file(s) contents of this module it appears that it is a Unix
file system. Perhaps this in why I cannot install it on a Windows WAMP
Server?

**Comment by JustCarmen** [comment]
I am sorry. I am afraid I can't help you.  The only thing this module does is providing an environment within webtrees to load MySqldumper (MyOOSDumper). I am not involved in the development of MySqldumper and his successor MyOOSDumper.

As far as I know MyOOSDumper should work in a windows environment. According to the [Mysqldumper ](http://www.mysqldumper.net/faq/#antwort1)website it should run under any operating system. Although the original author has stopped development (more information [here](https://github.com/JustCarmen/fancy_database_backup/issues/1)), I can't imagine the successor has dropped support for windows. The reason to switch to [MyOOSDumper ](http://doku.oos-shop.de/myoos-benutzerhandbuch/ueber-myoos/eine-einfuehrung-in-das-myoos-shopsystem/ueber-mysqldumper/ )is the support for PHP7 which the original has not. At least that was what I thought. But searching for an answer of your problem I've found out the original author has not fully dropped support. It seems the original program should work in PHP7 now. I need to test this but maybe it is a reason to switch back. Don't know if it would solve your problem though.

But you could drop a question at one of the support forums of either [MySQLDumper](http://forum.mysqldumper.de/index.php) or [MyOOSDumper](https://foren.myoos.de/viewforum.php?f=5). Maybe they can help you out.

**Comment by impartit** [comment]
OK Carmen - it was my fault in the location of the files on the WAMP
webserver and now all is working just fine. Thanks very much for your
support.

Regards

Neil
